# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeGenerated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(null=True)),
                ('code', models.CharField(max_length=10)),
                ('metadata', models.TextField(max_length=1000)),
            ],
        ),
    ]
